version: '3'
services:
    app:
        # 起動イメージ
        image: node:16
        tty: true
        # ホスト側のポート：コンテナのポート
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        # 起動時のカレントフォルダ
        working_dir: /app
        # 起動後に実行するコマンド
        command: npm start